In [54]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
def display_img(img):
    cv2.imshow("image",img)

    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [ ]:
#image shape is in img[y][x][B,G,R]

In [55]:
IMAGE_PATH = "wafflebotcam_test.JPG"
img = cv2.imread(IMAGE_PATH)
#display_img(img)

In [56]:
img.shape 

(719, 1702, 3)

In [57]:
RED_SQUARE_IMG = "red_test.png"
red_img = cv2.imread(RED_SQUARE_IMG)
#display_img(red_img)

In [52]:
red_img.shape

(504, 773, 3)

In [31]:
X_max = img

array([ 36,  28, 237], dtype=uint8)

array([[1., 0.],
       [0., 1.]])

In [116]:
#detect color red
#https://stackoverflow.com/questions/30331944/finding-red-color-in-image-using-python-opencv

img_hsv=cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

# create mask
lower_red = np.array([0,50,50])
upper_red = np.array([10,255,255])
mask0 = cv2.inRange(img_hsv, lower_red, upper_red)
lower_red = np.array([170,50,50])
upper_red = np.array([180,255,255])
mask1 = cv2.inRange(img_hsv, lower_red, upper_red)
mask = mask0+mask1
                    
# set my output img to zero everywhere except my mask
output_img = img.copy()
output_img[np.where(mask==0)] = 0
                    
# or your HSV image, which I *believe* is what you want
output_hsv = img_hsv.copy()
output_hsv[np.where(mask==0)] = 0
display_img(mask)


red_pixels = np.argwhere(mask>0)

In [93]:
output_hsv[np.where(mask!=0)][0]

array([  9,  51, 145], dtype=uint8)

In [129]:
#all x pixels?
ypx = red_pixels[:,0]
xpx = red_pixels[:,1]

In [134]:
x_coord = np.mean(ypx)
y_coord = np.mean(xpx)

In [135]:
display_img(mask)

In [128]:
mask.shape

(719, 1702)